server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: k8c1051.p.ssafy.io
      port: 6379
      password: mention
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/login
          filters:
#            - CustomFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - AuthorizationHeaderFilter
        - id: topic-service
          uri: lb://TOPIC-SERVICE
          predicates:
            - Path=/topic-service/**
          filters:
            - AuthorizationHeaderFilter

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, beans, busrefresh, httptrace

jwt:
  header: Authorization
  #echo 'spring-boot-security-jwt-ssafy-project-fairytalebox-spring-boot-security-jwt'|base64
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNzYWZ5LXByb2plY3QtZmFpcnl0YWxlYm94LXNwcmluZy1ib290LXNlY3VyaXR5LWp3dA==
  token-validity-in-milliseconds: 600000
